#ifndef _NAS782X_SYSCTL_H
#define _NAS782X_SYSCTL_H

#if !(defined(__KERNEL_STRICT_NAMES) || defined(__ASSEMBLY__))
#include <asm/types.h>
#endif /* !(__KERNEL_STRICT_NAMES || __ASSEMBLY__) */

#include <asm/arch/hardware.h>

/**
 * System block reset and clock control
 */
#define SYS_CTRL_PCI_STAT		(SYS_CONTROL_BASE + 0x20)
#define SYS_CTRL_CLK_SET_CTRL		(SYS_CONTROL_BASE + 0x2C)
#define SYS_CTRL_CLK_CLR_CTRL		(SYS_CONTROL_BASE + 0x30)
#define SYS_CTRL_RST_SET_CTRL		(SYS_CONTROL_BASE + 0x34)
#define SYS_CTRL_RST_CLR_CTRL		(SYS_CONTROL_BASE + 0x38)
#define SYS_CTRL_PLLSYS_CTRL		(SYS_CONTROL_BASE + 0x48)
#define SYS_CTRL_PLLSYS_KEY_CTRL	(SYS_CONTROL_BASE + 0x6C)
#define SYS_CTRL_GMAC_CTRL		(SYS_CONTROL_BASE + 0x78)

/* Scratch registers */
#define SYS_CTRL_SCRATCHWORD0		(SYS_CONTROL_BASE + 0xc4)
#define SYS_CTRL_SCRATCHWORD1		(SYS_CONTROL_BASE + 0xc8)
#define SYS_CTRL_SCRATCHWORD2		(SYS_CONTROL_BASE + 0xcc)
#define SYS_CTRL_SCRATCHWORD3		(SYS_CONTROL_BASE + 0xd0)

#define SYS_CTRL_PLLA_CTRL0		(SYS_CONTROL_BASE + 0x1F0)
#define SYS_CTRL_PLLA_CTRL1		(SYS_CONTROL_BASE + 0x1F4)
#define SYS_CTRL_PLLA_CTRL2		(SYS_CONTROL_BASE + 0x1F8)
#define SYS_CTRL_PLLA_CTRL3		(SYS_CONTROL_BASE + 0x1FC)

#define SYS_CTRL_GMAC_AUTOSPEED		3
#define SYS_CTRL_GMAC_RGMII		2
#define SYS_CTRL_GMAC_SIMPLE_MUX	1
#define SYS_CTRL_GMAC_CKEN_GTX		0

#define SYS_CTRL_CKCTRL_CTRL_ADDR	(SYS_CONTROL_BASE + 0x64)

#define SYS_CTRL_CKCTRL_PCI_DIV_BIT	0
#define SYS_CTRL_CKCTRL_SLOW_BIT	8

#ifndef __KERNEL_STRICT_NAMES
#ifndef __ASSEMBLY__

#endif /* __ASSEMBLY__ */
#endif /* __KERNEL_STRICT_NAMES */

#endif /* _NAS782X_SYSCTL_H */
